### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by impact-merlinmarek** [aas-core-works/aas-core3.0-golang#32]
Hi @mristin 

could you create a new release that includes the fixes #30 and #29?

Or is there a fixed release cycle for the sdk?

Thanks in advance

**Comment by mristin** [comment]
Sure! There's no fixed release cycle. I'll try to do it next Wed.

**Comment by mristin** [comment]
Thanks again for the ping, @impact-merlinmarek ! The new patch version is up: https://github.com/aas-core-works/aas-core3.0-golang/releases/tag/v1.0.4
